
language: java
jdk:
- oraclejdk11
script:
- "./gradlew compatTest5.6.4"
branches:
  only:
  - main
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: money-trasfer-api-act-pasd
  on:
    repo: gtekle/money-trasfer-api-act-pasd
    branch: main
  skip_cleanup: 'true'